# This is a basic workflow that is manually triggered

name: Demo


on:  
    workflow_dispatch:
    
jobs:
  
#  execute-test:
  ReadyAPI_TestCase:
    
    runs-on: self-hosted

    
    steps:
   
    - name: Demo
      working-directory: 'C:\Users\chandra.bollareddy\AppData\Local\Programs\SmartBear\ReadyAPI-3.43.1\bin'
      run: |
     
        C:\Users\chandra.bollareddy\AppData\Local\Programs\SmartBear\ReadyAPI-3.43.1\bin\testrunner.bat "-sDemo_TestSuite" -r -a -j "-fD:\ReadyAPI Reports" "-RJUnit-Style HTML Report" -FXML "-EDefault environment" D:\Demo-readyapi-project
